version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/raf924/connector-api
    versions:
    - 1.0.0-alpha.4
    - 1.0.0-alpha.6
  - dependency-name: github.com/raf924/bot
    versions:
    - 1.0.0-alpha.14
    - 1.0.0-alpha.15
    - 1.0.0-alpha.16
    - 1.0.0-alpha.21
  - dependency-name: github.com/raf924/bot-grpc-relay
    versions:
    - 1.0.0-alpha.17
  - dependency-name: google.golang.org/api
    versions:
    - 0.44.0
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.5.2
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.37.0
